# -*- coding: utf-8 -*-
"""Text-Mining Sentiment Analysis Assignment_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SHUqgCIJjCYTYqoMRkcR4-YtOnIaDeTT
"""

#Import the Python libraries needed for data handling, visualization, and modeling.
import pandas as pd
import numpy as np
import re
import time
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.decomposition import TruncatedSVD
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from bs4 import BeautifulSoup

#Download the Kaggle dataset and save the local directory path
import kagglehub

path = kagglehub.dataset_download("jessicali9530/kuc-hackathon-winter-2018")

print("Path to dataset files:", path)

import os

# List the contents of the directory
print(os.listdir(path))

#Load a CSV file into a pandas DataFrame.
data = pd.read_csv(os.path.join(path, 'drugsComTrain_raw.csv'))

#Display data in the notebook output (usually to preview a DataFrame or variable contents)
data

#Compute summary statistics for the dataset’s numeric columns.
data.describe()

#Review column data types and non-null counts to assess data quality.
data.info()

#Check the number of rows and columns in the DataFrame
data.shape

#Inspect column names to understand the dataset schema.
data.columns

#Inspect the DataFrame index to understand row identifiers/ordering.
data.index

#Temporarily change pandas display settings to show more columns/text when previewing the data.
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)
data.head(5)

data.tail(5)

pd.reset_option('display.max_columns')
pd.reset_option('display.max_colwidth')
data.head(5)

#Convert the date column from strings into proper datetime values.
data["date"] = pd.to_datetime(data["date"], format="%d-%b-%y")

#Format datetime values into a standardized YYYY-MM-DD string format.
data["date"] = data["date"].dt.strftime("%Y-%m-%d")

"""**Exploratory Data Analysis**

Visualize the distribution of review ratings to understand class balance in the dataset.
This helps determine whether the sentiment models may become biased toward positive or negative predictions due to imbalanced data.
"""

data['date'] = pd.to_datetime(data['date'])
data1 = data
data1 = data1.set_index('date')
plt.plot(data1['review'].resample('M').count())
plt.xlabel('Year')
plt.ylabel('Number of reviews')
plt.title('Number of reviews per year')
plt.show()

"""Examine how review ratings vary over time using the date field.
This checks for temporal trends that could influence sentiment patterns, such as shifts in user satisfaction across years.
"""

ax = sns.barplot(data=data, x='rating', y='rating', estimator=lambda x: len(x) / len(data) * 100)
ax.set(ylabel="Percent")
plt.title('Distribution of Customer Rating')
plt.show()

"""Analyze the relationship between review ratings and review text length.
This explores whether longer reviews tend to be more positive or negative, which can affect how sentiment models interpret intensity.
"""

plt.plot(data1['rating'].resample('M').mean())
plt.xlabel('Year')
plt.ylabel('Rating')
plt.title('Average Monthly Customer Rating')
plt.ylim(0,10)
plt.show()

"""**Data Cleaning**"""

import html
import re

#Define clean_review() as a reusable helper for the workflow (so later cells can call it consistently).
def clean_review(t):
    t = "" if pd.isna(t) else str(t)
    t = html.unescape(t)
    t = re.sub(r"<br\s*/?>", " ", t)
    t = re.sub(r"[^A-Za-z\s']", " ", t)
    t = re.sub(r"\s+", " ", t).strip()

    if t == "":
        return "emptyreview"   # placeholder so VADER can score
    return t.lower()

data["text"] = data["review"].apply(clean_review)

#Define clean_text() as a reusable helper for the workflow (so later cells can call it consistently).
def clean_text(text):
    return BeautifulSoup(text, "html.parser").get_text()

data['text'] = data['review'].apply(clean_text)

data['text'][0]

data['text'][5]

"""**STOP WORDS**

**STEP 5: Apply Pretrained Models**
"""

# VADER

import nltk
import pandas as pd
from nltk.sentiment import SentimentIntensityAnalyzer
nltk.download('vader_lexicon') #import nltk

sid = SentimentIntensityAnalyzer()

# df must have df["review"]
data["text"] = data["review"].fillna("").astype(str)

# Compute the VADER sentiment score for each text entry
# polarity_scores() returns a dictionary with neg, neu, pos, and compound
# We extract only the "compound" score because it is the normalized overall sentiment (-1 to 1)
data["vader_compound"] = data["text"].apply(lambda t: sid.polarity_scores(t)["compound"])
data[["text", "vader_compound"]].head(5)

# Function to convert the continuous VADER compound score into categorical sentiment labels
# Default VADER thresholds:
#   >= 0.05  → Positive
#   <= -0.05 → Negative
#   Otherwise → Neutral
def vader_label(c, pos_thr=0.05, neg_thr=-0.05):
    if c >= pos_thr:
        return "pos"
    elif c <= neg_thr:
        return "neg"
    else:
        return "neu"
# Apply the labeling function to every compound score
# This transforms numeric sentiment into a classification task
data["vader_label"] = data["vader_compound"].apply(vader_label)

# Count how many texts fall into each sentiment category
data["vader_label"].value_counts()

data.sort_values("vader_compound", ascending=False)[["review", "vader_compound", "vader_label"]].head(5)

# Filter the dataset to only include extreme opinions
# rating == 10 → strongest positive sentiment
# rating == 1  → strongest negative sentiment
# want to look at what is negative and what is positive
data_best_worst = data[(data["rating"]==10) | (data["rating"]==1)].reset_index()

print(data_best_worst.loc[0, 'text'])
print()
sid.polarity_scores(data_best_worst.loc[0, 'text'])

print(data_best_worst.loc[10, 'text'])
print()
sid.polarity_scores(data_best_worst.loc[10, 'text'])

print(data_best_worst.loc[55, 'text'])
print()
sid.polarity_scores(data_best_worst.loc[55, 'text'])

"""**Visualize sentiments**"""

# Function to visualize sentiment scores as a heatmap
sns.set(rc={'figure.figsize':(30,1)})

def visualise_sentiments(data):
  sns.heatmap(pd.DataFrame(data).set_index("Sentence").T,center=0, annot=True, cmap = "PiYG")

# Visualize sentiment at both the sentence level and word level
visualise_sentiments({
    "Sentence":["SENTENCE"] + data_best_worst.loc[68, 'text'].split(),
    "Sentiment":[sid.polarity_scores(data_best_worst.loc[68, 'text'])["compound"]]
    + [sid.polarity_scores(word)["compound"] for word in data_best_worst.loc[68, 'text'].split()]
})
    # First value = compound sentiment of the entire review
    # Remaining values = compound sentiment for each individual word
    # This helps show which words contribute most to the overall polarity

visualise_sentiments({
    "Sentence":["SENTENCE"] + data_best_worst.loc[2, 'text'].split(),
    "Sentiment":[sid.polarity_scores(data_best_worst.loc[2, 'text'])["compound"]]
    + [sid.polarity_scores(word)["compound"] for word in data_best_worst.loc[2, 'text'].split()]
})

"""**TEXTBLOB**"""

from textblob import TextBlob

# Compute sentiment polarity using TextBlob
# polarity ranges from -1 (negative) to +1 (positive), similar to VADER compound
data["tb_polarity"] = data["text"].apply(lambda t: TextBlob(t).sentiment.polarity)

data[["text","tb_polarity"]].head(5)

# Convert TextBlob polarity scores into categorical sentiment labels
# Uses the same thresholds as VADER so results are comparable across models
def tb_label(p, pos_thr=0.05, neg_thr=-0.05):
    if p >= pos_thr:
        return "pos"
    elif p <= neg_thr:
        return "neg"
    else:
        return "neu"

# Apply the labeling function to each polarity score
# This turns regression-style output (-1 to 1) into classification labels
data["tb_label"] = data["tb_polarity"].apply(tb_label)

data["tb_label"].value_counts()

# This allows access to linguistic features such as sentiment, noun phrases, and tokenization
blob = TextBlob(data_best_worst.loc[0,"text"])
print(blob)
print()
print(blob.sentiment)

blob = TextBlob(data_best_worst.loc[12,"text"])
print(blob)
print()
print(blob.sentiment)

# define a function that accepts text and returns the polarity
def detect_sentiment(text):

    #Converts the text into textblob object and then retuns
    #the subjectivity.
    blob = TextBlob(text)

    # return the subjectivity
    return blob.sentiment.subjectivity

blob = TextBlob(data_best_worst.loc[12,"text"])
print(blob)
print()
print(blob.sentiment)

# Calculate TextBlob subjectivity score for each extreme review
# subjectivity ranges from 0 → objective/factual
#                         to 1 → opinionated/personal
# This helps analyze whether strong ratings are driven by emotion vs factual statements
data_best_worst["tb_subjectivity"] = data_best_worst["text"].apply(
    lambda t: TextBlob(t).sentiment.subjectivity
)

import matplotlib.pyplot as plt

# Create a histogram to visualize how subjective the extreme reviews are

plt.figure(figsize=(10,6))
plt.hist(data_best_worst["tb_subjectivity"], bins=50, color="blue", alpha=0.5)

plt.xlabel("Subjectivity")
plt.ylabel("Count")
plt.title("Distribution of TextBlob Subjectivity")
plt.show()

"""**Compare VADER & TEXTBLOB**"""

data[["vader_label","tb_label"]].value_counts()

# Identify reviews where the two models predict different sentiments
# This isolates difficult or ambiguous cases useful for error analysis
disagree = data[data["vader_label"] != data["tb_label"]]

disagree[["review","vader_label","tb_label"]].head(10)

# Compare how often VADER and TextBlob agree or disagree on sentiment classification
pair_counts = (
    data.groupby(["vader_label", "tb_label"])
      .size()
      .reset_index(name="count")
      .sort_values("count", ascending=False)
)

pair_counts.head(15)

# Create a confusion-style table comparing VADER vs TextBlob predictions
# Rows  → VADER predicted labels
# Columns → TextBlob predicted labels
# Each cell shows how many reviews fall into that combination
pd.crosstab(data["vader_label"], data["tb_label"])

# Normalized comparison table between VADER and TextBlob
# normalize="index" converts each row into percentages
# → Shows: given VADER predicted X, how often does TextBlob predict each class?
pd.crosstab(data["vader_label"], data["tb_label"], normalize="index").round(3)

# Another way to summarize agreement between VADER and TextBlob
# Produces a ranked table of all label pair combinations
(data.groupby(["vader_label","tb_label"])
     .size()
     .reset_index(name="count")
     .sort_values("count", ascending=False))

"""**TRANSFORMER TORCH**"""

!pip -q install transformers torch

# Import PyTorch (backend used by many HuggingFace models for tensor computation)
# Import the HuggingFace pipeline helper
import torch
from transformers import pipeline

# Load a pretrained transformer emotion classifier
# Uses DistilRoBERTa fine-tuned to detect emotions (joy, anger, sadness, etc.)
emo_clf = pipeline(
    "text-classification",
    model="j-hartmann/emotion-english-distilroberta-base",
    device=0 if torch.cuda.is_available() else -1
)

# Convert text column into a clean list of strings
# fillna prevents model errors caused by missing values
texts = data["text"].fillna("").astype(str).tolist()

# Store predictions
hf_emotion = []
hf_emotion_score = []

# Run inference in batches to avoid memory issues and improve speed
batch_size = 32
for i in range(0, len(texts), batch_size):
    batch = texts[i:i+batch_size]

    # truncation=True ensures long reviews are cut to model token limit
    preds = emo_clf(batch, truncation=True)

    # Save predicted label and confidence score
    hf_emotion.extend([p["label"] for p in preds])
    hf_emotion_score.extend([p["score"] for p in preds])

# Attach predictions back to dataset
data["hf_emotion"] = hf_emotion
data["hf_emotion_score"] = hf_emotion_score

# Convert multi-class emotion predictions into binary sentiment
# Positive emotions → "pos"
# All other emotions → "neg"
# This allows comparison with VADER and TextBlob (which are binary/ternary sentiment models)
def emotion_to_binary(e):
    e = str(e).lower().strip()
    if e in ["joy", "surprise"]:
        return "pos"
    else:
        return "neg"

# Apply conversion to transformer emotion predictions
data["hf_label"] = data["hf_emotion"].apply(emotion_to_binary)

# Check distribution of transformer-based sentiment labels
# dropna=False ensures missing values (if any) are also counted
print(data["hf_label"].value_counts(dropna=False))

# Verify whether any predictions failed and produced NaN labels
# Useful data quality check before evaluation
print("Any NaNs in hf_label?", data["hf_label"].isna().sum())

data["hf_label"].value_counts()

"""#Step 6: Analyze and Review Results

"""

# Create a clean evaluation dataset containing only relevant fields
# Keeps the original review plus predictions from all three models
final_df = data[[
    "drugName",
    "text",

    "vader_label",
    "vader_compound",

    "tb_label",
    "tb_polarity",

    "hf_label",
    "hf_emotion",
    "hf_emotion_score",

]].copy()

# Compare VADER vs TextBlob predictions using the cleaned evaluation dataset
# Helps evaluate agreement after model outputs were consolidated
pd.crosstab(final_df["vader_label"], final_df["tb_label"])

# Compare VADER sentiment predictions with the transformer-based binary sentiment
# Shows how often the rule-based model and the deep learning model agree or disagree
pd.crosstab(final_df["vader_label"], final_df["hf_label"])

# Compare TextBlob sentiment predictions with the transformer-based binary sentiment
# Useful for identifying whether the lexicon-based model aligns with the deep learning model
pd.crosstab(final_df["tb_label"], final_df["hf_label"])

# Summary statistics of VADER compound scores within each predicted label
# Helps verify that numeric sentiment scores align with their assigned categories
# (e.g., positive labels should have higher average compound values)
final_df.groupby("vader_label")["vader_compound"].describe()

# Examine confidence levels of the transformer model by predicted sentiment
# Shows how strongly the model believes its positive vs negative classifications
final_df.groupby("hf_label")["hf_emotion_score"].describe()

# Summary statistics of TextBlob polarity scores for each predicted sentiment class
# Useful to confirm that negative labels have lower polarity values and positive labels have higher ones

final_df.groupby("tb_label")["tb_polarity"].describe()

final_df.head(5)

tmp = final_df.copy()

# Measure disagreement between model confidence scores
# Absolute difference shows how far apart the models are numerically
# VADER vs TextBlob
tmp["vader_tb_gap"] = (tmp["vader_compound"] - tmp["tb_polarity"]).abs()

# VADER vs Transformer
# Note: hf_emotion_score is probability confidence, not sentiment polarity,
# so large gaps may reflect scale differences rather than true disagreemen
tmp["vader_hf_gap"] = (tmp["vader_compound"] - tmp["hf_emotion_score"]).abs()

# TextBlob vs Transformer
tmp["tb_hf_gap"] = (tmp["tb_polarity"] - tmp["hf_emotion_score"]).abs()

# Summarize disagreement statistics across the dataset
tmp[["vader_tb_gap","vader_hf_gap","tb_hf_gap"]].describe()

final_df[final_df["vader_label"] != final_df["tb_label"]][
    ["drugName","text","vader_label","vader_compound","tb_label","tb_polarity"]
].head(10)

final_df[
    (final_df["hf_label"] != final_df["vader_label"]) &
    (final_df["hf_label"] != final_df["tb_label"])
][
    ["drugName","text","hf_emotion","hf_label","hf_emotion_score",
     "vader_label","vader_compound","tb_label","tb_polarity"]
].head(10)

"""**EXPORT FOR HUMAN LABELS**"""

sample100_final = final_df.sample(n=100, random_state=42).copy()

sample100_final.head(10)

sample100_final.to_csv("final_df_sample100.csv", index=False)

"""**Model comparison to human labels**"""

final = pd.read_csv("/content/drive/MyDrive/Spring MSBA/Text mining/human_label_sample_100.csv")
final.head(5)

final.columns

"""**Confusion Matrix & Model Evaluation**"""

# Import evaluation metrics from scikit-learn
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

# Standardize label formatting across all models and human annotations
# Ensures fair comparison by removing case differences and extra spaces
# Example: " Positive " → "positive"
for col in ["human_label","vader_label","tb_label","hf_label"]:
    final[col] = final[col].astype(str).str.lower().str.strip()

# Define consistent label ordering for evaluation
labels = ["neg","neu","pos"]

# Function to evaluate a sentiment model against human labels
# Produces a confusion matrix formatted as a readable table
def evaluate(name, y_true, y_pred):

    print(f"\n===== {name} =====")

    # Compute confusion matrix using fixed label order
    # Rows = actual (human labels)
    # Columns = predicted labels
    cm = confusion_matrix(y_true, y_pred, labels=labels)

    # Convert matrix to labeled DataFrame for clarity
    cm_df = pd.DataFrame(cm,
                         index=[f"True_{l}" for l in labels],
                         columns=[f"Pred_{l}" for l in labels])
    display(cm_df)

    print("Accuracy:", round(accuracy_score(y_true, y_pred),4))
    print(classification_report(y_true, y_pred, labels=labels, zero_division=0))

# Evaluate each sentiment model against the human ground truth labels
# Produces a confusion matrix for each model
evaluate("VADER", final["human_label"], final["vader_label"])
evaluate("TextBlob", final["human_label"], final["tb_label"])
evaluate("Transformer", final["human_label"], final["hf_label"])

# Create a performance summary comparing model accuracies
# Accuracy = percentage of predictions that match the human label
summary = pd.DataFrame({
    "Model":["VADER","TextBlob","Transformer"],
    "Accuracy":[
        accuracy_score(final["human_label"], final["vader_label"]),
        accuracy_score(final["human_label"], final["tb_label"]),
        accuracy_score(final["human_label"], final["hf_label"])
    ]
}).sort_values("Accuracy", ascending=False)

summary

# Create boolean flags indicating whether each model predicted correctly
# True  → model matches the human label
# False → model made an error
# Useful for filtering success/failure examples later
final["vader_correct"] = final["vader_label"] == final["human_label"]
final["tb_correct"] = final["tb_label"] == final["human_label"]
final["hf_correct"] = final["hf_label"] == final["human_label"]

# Count how many predictions each model got right vs wrong
# .sum() works because True = 1 and False = 0 in pandas
correct_counts = pd.DataFrame({
    "Model": ["VADER", "TextBlob", "Transformer"],
    "Correct": [
        final["vader_correct"].sum(),
        final["tb_correct"].sum(),
        final["hf_correct"].sum()
    ],
    "Incorrect": [
        (~final["vader_correct"]).sum(),
        (~final["tb_correct"]).sum(),
        (~final["hf_correct"]).sum()
    ]
})

correct_counts

# Compute accuracy manually from correct vs incorrect counts
# Accuracy = Correct / Total predictions
correct_counts["Accuracy"] = correct_counts["Correct"] / (correct_counts["Correct"] + correct_counts["Incorrect"])

# Rank models from best to worst performance
correct_counts.sort_values("Accuracy", ascending=False)

"""**VADER Success**"""

# Display random examples where a model predicted correctly
# Helps qualitatively understand what types of text the model handles well
def show_success_examples(df, model_label, score_col, model_name, n=3):

 # Select rows where model prediction matches the human label
    success = df[df[model_label] == df["human_label"]].sample(n, random_state=42)

 # Select rows where model prediction matches the human label
    for i, row in enumerate(success.itertuples(), 1):
        print(f"\n{model_name} Success Example {i}:")
        print("Text:", row.text)
        print(f"{model_name} prediction:", row.__getattribute__(model_label),
              f"({round(row.__getattribute__(score_col),3)})")
        print("Human label:", row.human_label)

show_success_examples(final, "vader_label", "vader_compound", "VADER")

"""**TextBlob Success**"""

show_success_examples(final, "tb_label", "tb_polarity", "TextBlob")

"""**Transformer Success**"""

show_success_examples(final, "hf_label", "hf_score", "Transformer")

"""**Failures**"""

# Display random examples where a model predicted incorrectly
# Useful for diagnosing weaknesses and understanding model errors
def show_failure_examples(df, model_label, score_col, model_name, n=3):

    # Select rows where model prediction does NOT match the human label
    failures = df[df[model_label] != df["human_label"]].sample(n, random_state=42)

    # Loop through sampled failure cases and print formatted output
    for i, row in enumerate(failures.itertuples(), 1):
        print(f"\n{model_name} Failure Example {i}:")
        print("Text:", row.text)
        print(f"{model_name} prediction:", row.__getattribute__(model_label),
              f"({round(row.__getattribute__(score_col),3)})")
        print("Actual sentiment:", row.human_label)

#Vader Failures

show_failure_examples(final, "vader_label", "vader_compound", "VADER")

#TextBlob Failures

show_failure_examples(final, "tb_label", "tb_polarity", "TextBlob")

#Transformer Failures

show_failure_examples(final, "hf_label", "hf_score", "Transformer")

"""Model Comparison 5 Criterion Table"""

# Import required libraries for benchmarking and evaluation
import time                    # measure runtime speed
import numpy as np             # numerical operations
import pandas as pd            # tables and data handling
from sklearn.metrics import accuracy_score  # compare predictions to human labels

# Helper functions used throughout the comparison

def sample_texts(df, text_col="text", n=500, seed=42):
    # Randomly select a subset of reviews so speed tests are fair and consistent
    s = df[text_col].fillna("").astype(str)
    n = min(n, len(s))
    return s.sample(n, random_state=seed).tolist()

def model_accuracy(df, pred_col, truth_col="human_label"):
    # Compute accuracy by comparing model predictions to human labeled sentiment
    d = df.dropna(subset=[pred_col, truth_col]).copy()
    return accuracy_score(d[truth_col], d[pred_col])

# Measure how long each sentiment model takes to process the same text

def vader_speed(texts, repeats=3):
    # VADER scoring runtime
    times = []
    for _ in range(repeats):
        start = time.perf_counter()
        _ = [sid.polarity_scores(t)["compound"] for t in texts]
        end = time.perf_counter()
        times.append(end - start)
    return float(np.mean(times))

def textblob_speed(texts, repeats=3):
    # TextBlob scoring runtime
    times = []
    for _ in range(repeats):
        start = time.perf_counter()
        _ = [TextBlob(t).sentiment.polarity for t in texts]
        end = time.perf_counter()
        times.append(end - start)
    return float(np.mean(times))

def transformer_speed(texts, batch_size=32, repeats=3):
    # Transformer runtime (batched because neural models process batches efficiently)
    times = []
    for _ in range(repeats):
        start = time.perf_counter()
        for i in range(0, len(texts), batch_size):
            _ = emo_clf(texts[i:i+batch_size], truncation=True)
        end = time.perf_counter()
        times.append(end - start)
    return float(np.mean(times))

# Run performance evaluation for all models

N_SPEED = 500  # number of reviews used for speed testing
texts = sample_texts(final, n=N_SPEED)

# Measure runtime
vader_sec = vader_speed(texts)
tb_sec    = textblob_speed(texts)
hf_sec    = transformer_speed(texts)

# Measure accuracy using human labeled ground truth
vader_acc = model_accuracy(final, "vader_label")
tb_acc    = model_accuracy(final, "tb_label")
hf_acc    = model_accuracy(final, "hf_label")

print("Speed (seconds):", vader_sec, tb_sec, hf_sec)
print("Accuracy:", vader_acc, tb_acc, hf_acc)

# Identify which model performs best on each quantitative metric

def winner_speed(v, t, h):
    # Lower runtime is better
    d = {"VADER": v, "TextBlob": t, "Transformer": h}
    return min(d, key=d.get)

def winner_accuracy(v, t, h):
    # Higher accuracy is better
    d = {"VADER": v, "TextBlob": t, "Transformer": h}
    return max(d, key=d.get)

speed_winner = winner_speed(vader_sec, tb_sec, hf_sec)
acc_winner   = winner_accuracy(vader_acc, tb_acc, hf_acc)

print("Speed winner:", speed_winner)
print("Accuracy winner:", acc_winner)

# Format numbers nicely for presentation
def fmt_sec(x): return f"{x:.2f} sec / {N_SPEED} reviews"
def fmt_pct(x): return f"{x*100:.1f}%"

# Create structured comparison table summarizing performance and qualitative strengths
rows = [
    {
        "Criterion": "Speed",
        "VADER": fmt_sec(vader_sec),
        "TextBlob": fmt_sec(tb_sec),
        "Transformer": fmt_sec(hf_sec),
        "Winner": speed_winner,
        "Justification": "Lower runtime is faster"
    },
    {
        "Criterion": "Accuracy (human labels)",
        "VADER": fmt_pct(vader_acc),
        "TextBlob": fmt_pct(tb_acc),
        "Transformer": fmt_pct(hf_acc),
        "Winner": acc_winner,
        "Justification": "Highest agreement with human labels"
    },
    {
        "Criterion": "Handles emphasis (caps/punctuation)",
        "VADER": "Excellent",
        "TextBlob": "Weak",
        "Transformer": "Good",
        "Winner": "VADER",
        "Justification": "Rule based intensity handling"
    },
    {
        "Criterion": "Handles negation",
        "VADER": "Good",
        "TextBlob": "Better",
        "Transformer": "Good",
        "Winner": "TextBlob",
        "Justification": "Better polarity shifts for phrases like 'not bad'"
    },
    {
        "Criterion": "Context understanding",
        "VADER": "Weak",
        "TextBlob": "Weak",
        "Transformer": "Strong",
        "Winner": "Transformer",
        "Justification": "Learns contextual meaning"
    },
]

comparison = pd.DataFrame(rows)
comparison

"""**Final Recommendation**

Recommended Model: Transformer (DistilRoBERTa emotion model)

The transformer works best here because it reads the review more like a person would. Instead of reacting to individual positive or negative words, it looks at the full sentence and understands how the ideas connect. Drug reviews often include explanations, side effects, trade-offs, and mixed opinions in the same paragraph, so context matters a lot. Even though it had slightly worse measured accuracy, its predictions often align better with human reasoning than the rule-based models.

**When to Choose Another Model**

Use VADER when

- You need very fast scoring or real-time processing
- The text is short (tweets, short comments, headlines)
- Punctuation and emphasis matter (ALL CAPS, !!!)
- You want transparent, rule-based behavior you can easily explain

Use TextBlob when

- You want a simple baseline with stable polarity values
- Basic negation matters (e.g., “not bad”, “not effective”)
- You are running on limited hardware
- You need quick sentiment without loading large models

In short: VADER for speed and lightweight production use, TextBlob for a simple interpretable baseline, and the transformer when deeper understanding of longer reviews is more important than efficiency.

**Summary**

Overall, the transformer is the best choice when you care most about understanding what the reviewer actually means, especially in longer and more detailed reviews. VADER is useful when you need quick, real-time sentiment scoring, and TextBlob works well as a simple baseline that handles basic polarity shifts. In practice, the transformer gives the most thoughtful interpretation, while the other two are helpful when speed, simplicity, or low resource usage matter more.
"""

from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt

# Function to plot confusion matrices for all models side-by-side
def plot_all_confusions(df):
    # Define the sentiment categories in fixed order
    labels = ["neg", "neu", "pos"]

    # Map readable model names to their prediction columns
    models = {
        "VADER": "vader_label",
        "TextBlob": "tb_label",
        "Transformer": "hf_label"
    }

    # Create one row with three plots for comparison
    fig, axes = plt.subplots(1, 3, figsize=(15, 4), dpi=120)

    # Loop through each model and generate its confusion matrix
    for ax, (name, col) in zip(axes, models.items()):
        # Remove rows missing either human or model labels
        df_eval = df.dropna(subset=["human_label", col]).copy()

        # Compute normalized confusion matrix (proportions instead of raw counts)
        cm = confusion_matrix(
            df_eval["human_label"],
            df_eval[col],
            labels=labels,
            normalize="true"
        )

        # Plot matrix using a consistent blue color scale
        disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=labels)
        disp.plot(
            ax=ax,
            cmap="Blues",
            colorbar=False,
            values_format=".2f"
        )

        # Remove grid lines and borders to make the plot cleaner
        ax.grid(False)
        for spine in ax.spines.values():
            spine.set_visible(False)

        # Add axis labels and title for each model
        ax.set_title(name)
        ax.set_xlabel("Predicted")
        ax.set_ylabel("Actual")

    # Add overall title and format spacing
    plt.suptitle("Model Comparison vs Human Labels", fontsize=14)
    plt.tight_layout()
    plt.show()

# Run the visualization on the final dataset
plot_all_confusions(final)